/*
===============================================================================
*             Texas Instruments OMAP(TM) Platform Software
* (c) Copyright Texas Instruments, Incorporated. All Rights Reserved.
*
* Use of this software is controlled by the terms and conditions found
* in the license agreement under which this software has been supplied.
*
===============================================================================
*/
//
//  File: oem_pinmux.c
//
// This file controls the GPIO pin functions selected during system power states (D0..D4).
// It is very platform dependent code.
//
#include <windows.h>
#include <oal.h>
#include <oalex.h>
#include <ceddk.h>
#include <ceddkex.h>
#include <omap35xx.h>

//-----------------------------------------------------------------------------
// macros

// generates static arrays with the following format
//      static DEVICE_PINMUX_ENTRY_t OMAP_DEVICE_MCBSP2_D0[] = {...}
//      static DEVICE_PINMUX_ENTRY_t OMAP_DEVICE_MCBSP2_D4[] = {...}
//
#define DEVICE_PINMUX_BEGIN(devId, state) static DEVICE_PINMUX_ENTRY_t devId##_##state[] = { 
#define DEVICE_PINMUX_ENTRY(field, val)   {(DWORD)&((OMAP_SYSC_PADCONFS_REGS*)0)->field, val},
#define DEVICE_PINMUX_END(devId, state)   { -1, 0 }};

// generates static arrays with the following format
//      static DEVICE_PINMUX_t _MuxTbl_OMAP_DEVICE_MCBSP2 = {
//                                                           &OMAP_DEVICE_MCBSP2_D?,
//                                                           &OMAP_DEVICE_MCBSP2_D?,
//                                                           &OMAP_DEVICE_MCBSP2_D?,
//                                                           &OMAP_DEVICE_MCBSP2_D?,
//                                                           &OMAP_DEVICE_MCBSP2_D?
//                                                           }
//
#define MAP_DEVICESTATE_BEGIN(devId)      static DEVICE_PINMUX_t _MuxTbl_##devId = {
#define MAP_DEVICESTATE_D0(devId, state)    devId##_##state,
#define MAP_DEVICESTATE_D1(devId, state)    devId##_##state,
#define MAP_DEVICESTATE_D2(devId, state)    devId##_##state,
#define MAP_DEVICESTATE_D3(devId, state)    devId##_##state,
#define MAP_DEVICESTATE_D4(devId, state)    devId##_##state
#define MAP_DEVICESTATE_END(devId)        };

#define DEVICESTATE_MUX_NAME(devId)       &_MuxTbl_##devId

//-----------------------------------------------------------------------------
// structures
typedef struct {
    DWORD       offset;
    DWORD       value;
} DEVICE_PINMUX_ENTRY_t;

typedef  DEVICE_PINMUX_ENTRY_t* DEVICE_PINMUX_t[5];

//------------------------------------------------------------------------------
// static variables
static OMAP_SYSC_PADCONFS_REGS *_pSyscConfigContext;
static DEVICE_PINMUX_t         *_rgDeviceMux[OMAP_DEVICE_COUNT];        

//-----------------------------------------------------------------------------
// OMAP_DEVICE_HSOTGUSB
DEVICE_PINMUX_BEGIN(OMAP_DEVICE_HSOTGUSB, D0)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_HSUSB0_CLK, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_HSUSB0_STP, (INPUT_DISABLE | PULL_UP | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_HSUSB0_DIR, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_HSUSB0_NXT, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_HSUSB0_DATA0, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_HSUSB0_DATA1, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_HSUSB0_DATA2, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_HSUSB0_DATA3, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_HSUSB0_DATA4, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_HSUSB0_DATA5, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_HSUSB0_DATA6, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_HSUSB0_DATA7, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
DEVICE_PINMUX_END(OMAP_DEVICE_HSOTGUSB, D0)

DEVICE_PINMUX_BEGIN(OMAP_DEVICE_HSOTGUSB, D4)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_HSUSB0_CLK, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_HSUSB0_STP, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_HSUSB0_DIR, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_HSUSB0_NXT, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_HSUSB0_DATA0, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_HSUSB0_DATA1, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_HSUSB0_DATA2, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_HSUSB0_DATA3, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_HSUSB0_DATA4, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_HSUSB0_DATA5, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_HSUSB0_DATA6, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_HSUSB0_DATA7, (PADCONF_PIN_NOT_USED))
DEVICE_PINMUX_END(OMAP_DEVICE_HSOTGUSB, D4)

//-----------------------------------------------------------------------------
// OMAP_DEVICE_USBHOST1
// UNDONE: pin configuration needs to be verified
//
DEVICE_PINMUX_BEGIN(OMAP_DEVICE_USBHOST1, D0)
    // 12 pin ULPI transceiver on MM1, configure USB port1 pins for ULPI PHY mode
    // Note that this port configuration is only supported by the EHCI driver.
    // Note that this port configuration requires a daughter card with a high speed 12-pin ULPI transceiver connected these pins.
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_ETK_CLK, (INPUT_DISABLE | PULL_UP       | MUX_MODE_3))  // HSUSB1_STP
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_ETK_CTL, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_3))  // HSUSB1_CLK
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_ETK_D0, (INPUT_ENABLE   | PULL_INACTIVE | MUX_MODE_3))  // HSUSB1_DATA0
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_ETK_D1, (INPUT_ENABLE   | PULL_INACTIVE | MUX_MODE_3))  // HSUSB1_DATA1
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_ETK_D2, (INPUT_ENABLE   | PULL_INACTIVE | MUX_MODE_3))  // HSUSB1_DATA2
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_ETK_D3, (INPUT_ENABLE   | PULL_INACTIVE | MUX_MODE_3))  // HSUSB1_DATA7
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_ETK_D4, (INPUT_ENABLE   | PULL_INACTIVE | MUX_MODE_3))  // HSUSB1_DATA4
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_ETK_D5, (INPUT_ENABLE   | PULL_INACTIVE | MUX_MODE_3))  // HSUSB1_DATA5
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_ETK_D6, (INPUT_ENABLE   | PULL_INACTIVE | MUX_MODE_3))  // HSUSB1_DATA6
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_ETK_D7, (INPUT_ENABLE   | PULL_INACTIVE | MUX_MODE_3))  // HSUSB1_DATA3
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_ETK_D8, (INPUT_ENABLE   | PULL_INACTIVE | MUX_MODE_3))  // HSUSB1_DIR
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_ETK_D9, (INPUT_ENABLE   | PULL_INACTIVE | MUX_MODE_3))  // HSUSB1_NXT
DEVICE_PINMUX_END(OMAP_DEVICE_USBHOST1, D0)

DEVICE_PINMUX_BEGIN(OMAP_DEVICE_USBHOST1, D4)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_ETK_CLK, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_ETK_CTL, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_ETK_D0, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_ETK_D1, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_ETK_D2, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_ETK_D3, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_ETK_D4, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_ETK_D5, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_ETK_D6, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_ETK_D7, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_ETK_D8, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_ETK_D9, (PADCONF_PIN_NOT_USED))
DEVICE_PINMUX_END(OMAP_DEVICE_USBHOST1, D4)

//-----------------------------------------------------------------------------
// OMAP_DEVICE_USBHOST2
// UNDONE: pin configuration needs to be verified
//
DEVICE_PINMUX_BEGIN(OMAP_DEVICE_USBHOST2,	D0)
DEVICE_PINMUX_END(OMAP_DEVICE_USBHOST2,		D0)
DEVICE_PINMUX_BEGIN(OMAP_DEVICE_USBHOST2,	D4)
DEVICE_PINMUX_END(OMAP_DEVICE_USBHOST2,		D4)

//-----------------------------------------------------------------------------
// OMAP_DEVICE_USBHOST3
// UNDONE: pin configuration needs to be verified
//
DEVICE_PINMUX_BEGIN(OMAP_DEVICE_USBHOST3, D0)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MMC2_DAT5, (INPUT_DISABLE | PULL_UP | MUX_MODE_5))      /*HSUSB3_TLL_STP*/
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MMC2_DAT6, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_5)) /*HSUSB3_TLL_DIR*/
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MMC2_DAT7, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_5)) /*HSUSB3_TLL_NXT*/
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP3_DX, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_5)) /*HSUSB3_TLL_DATA4*/
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP3_DR, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_5)) /*HSUSB3_TLL_DATA5*/
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP3_CLKX, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_5))/*HSUSB3_TLL_DATA6*/
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP3_FSX, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_5))/*HSUSB3_TLL_DATA7*/
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_UART1_CTS, (INPUT_DISABLE | PULL_INACTIVE| MUX_MODE_5)) /*HSUSB3_TLL_CLK*/
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP4_CLKX, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_5))/*HSUSB3_TLL_DATA1*/
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP4_DR, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_5)) /*HSUSB3_TLL_DATA0*/
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP4_DX, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_5)) /*HSUSB3_TLL_DATA2*/
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP4_FSX, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_5))/*HSUSB3_TLL_DATA3*/
DEVICE_PINMUX_END(OMAP_DEVICE_USBHOST3, D0)

DEVICE_PINMUX_BEGIN(OMAP_DEVICE_USBHOST3, D4)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MMC2_DAT5, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MMC2_DAT6, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MMC2_DAT7, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP3_DX, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP3_DR, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP3_CLKX, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP3_FSX, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_UART1_CTS, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP4_CLKX, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP4_DR, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP4_DX, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP4_FSX, (PADCONF_PIN_NOT_USED))
DEVICE_PINMUX_END(OMAP_DEVICE_USBHOST3, D4)

//-----------------------------------------------------------------------------
// OMAP_DEVICE_MCBSP2
DEVICE_PINMUX_BEGIN(OMAP_DEVICE_MCBSP2, D0)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP2_DX, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP2_DR, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP2_CLKX, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP2_FSX, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
DEVICE_PINMUX_END(OMAP_DEVICE_MCBSP2, D0)

DEVICE_PINMUX_BEGIN(OMAP_DEVICE_MCBSP2, D4)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP2_DX, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP2_DR, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP2_CLKX, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP2_FSX, (PADCONF_PIN_NOT_USED))
DEVICE_PINMUX_END(OMAP_DEVICE_MCBSP2, D4)

//-----------------------------------------------------------------------------
// OMAP_DEVICE_MCBSP3
DEVICE_PINMUX_BEGIN(OMAP_DEVICE_MCBSP3, D0)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP3_DX, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP3_DR, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP3_CLKX, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP3_FSX, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
DEVICE_PINMUX_END(OMAP_DEVICE_MCBSP3, D0)

DEVICE_PINMUX_BEGIN(OMAP_DEVICE_MCBSP3, D4)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP3_DX, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP3_DR, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP3_CLKX, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP3_FSX, (PADCONF_PIN_NOT_USED))
DEVICE_PINMUX_END(OMAP_DEVICE_MCBSP3, D4)

//-----------------------------------------------------------------------------
// OMAP_DEVICE_MCBSP4
// Note: EVM uses these pins as GPIO (MUX_MODE_4)
DEVICE_PINMUX_BEGIN(OMAP_DEVICE_MCBSP4, D0)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP4_DR, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP4_DX, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP4_CLKX, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP4_FSX, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
DEVICE_PINMUX_END(OMAP_DEVICE_MCBSP4, D0)

DEVICE_PINMUX_BEGIN(OMAP_DEVICE_MCBSP4, D4)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP4_DR, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP4_DX, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP4_CLKX, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCBSP4_FSX, (PADCONF_PIN_NOT_USED))
DEVICE_PINMUX_END(OMAP_DEVICE_MCBSP4, D4)

//-----------------------------------------------------------------------------
// OMAP_DEVICE_HDQ
DEVICE_PINMUX_BEGIN(OMAP_DEVICE_HDQ, D0)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_HDQ_SIO, (INPUT_ENABLE | PULL_UP | MUX_MODE_0))
DEVICE_PINMUX_END(OMAP_DEVICE_HDQ, D0)

DEVICE_PINMUX_BEGIN(OMAP_DEVICE_HDQ, D4)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_HDQ_SIO, (PADCONF_PIN_NOT_USED))
DEVICE_PINMUX_END(OMAP_DEVICE_HDQ, D4)

//-----------------------------------------------------------------------------
// OMAP_DEVICE_I2C1
DEVICE_PINMUX_BEGIN(OMAP_DEVICE_I2C1, D0)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_I2C1_SCL, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_I2C1_SDA, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
DEVICE_PINMUX_END(OMAP_DEVICE_I2C1, D0)

//-----------------------------------------------------------------------------
DEVICE_PINMUX_BEGIN(OMAP_DEVICE_I2C1, D4)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_I2C1_SCL, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_I2C1_SDA, (PADCONF_PIN_NOT_USED))
DEVICE_PINMUX_END(OMAP_DEVICE_I2C1, D4)

//-----------------------------------------------------------------------------
// OMAP_DEVICE_I2C2
DEVICE_PINMUX_BEGIN(OMAP_DEVICE_I2C2, D0)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_I2C2_SCL, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_I2C2_SDA, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
DEVICE_PINMUX_END(OMAP_DEVICE_I2C2, D0)

DEVICE_PINMUX_BEGIN(OMAP_DEVICE_I2C2, D4)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_I2C2_SCL, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_I2C2_SDA, (PADCONF_PIN_NOT_USED))
DEVICE_PINMUX_END(OMAP_DEVICE_I2C2, D4)

//-----------------------------------------------------------------------------
// OMAP_DEVICE_I2C3
DEVICE_PINMUX_BEGIN(OMAP_DEVICE_I2C3, D0)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_I2C3_SCL, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_I2C3_SDA, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
DEVICE_PINMUX_END(OMAP_DEVICE_I2C3, D0)

DEVICE_PINMUX_BEGIN(OMAP_DEVICE_I2C3, D4)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_I2C3_SCL, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_I2C3_SDA, (PADCONF_PIN_NOT_USED))
DEVICE_PINMUX_END(OMAP_DEVICE_I2C3, D4)

//-----------------------------------------------------------------------------
// OMAP_DEVICE_I2C4
/*
DEVICE_PINMUX_BEGIN(OMAP_DEVICE_I2C4, D0)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_I2C4_SCL, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_I2C4_SDA, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
DEVICE_PINMUX_END(OMAP_DEVICE_I2C4, D0)

DEVICE_PINMUX_BEGIN(OMAP_DEVICE_I2C4, D4)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_I2C4_SCL, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_I2C4_SDA, (PADCONF_PIN_NOT_USED))
DEVICE_PINMUX_END(OMAP_DEVICE_I2C4, D4)
*/

//-----------------------------------------------------------------------------
// OMAP_DEVICE_MCSPI1
DEVICE_PINMUX_BEGIN(OMAP_DEVICE_MCSPI1, D0)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCSPI1_CLK, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCSPI1_SIMO, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCSPI1_SOMI, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCSPI1_CS0, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    //DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCSPI1_CS1, (INPUT_DISABLE | PULL_DOWN | MUX_MODE_0))
    //DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCSPI1_CS3, (INPUT_ENABLE | PULL_DOWN | MUX_MODE_0))
    //DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCSPI1_CS2, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_4))/*GPIO_176*/    
DEVICE_PINMUX_END(OMAP_DEVICE_MCSPI1, D0)

DEVICE_PINMUX_BEGIN(OMAP_DEVICE_MCSPI1, D4)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCSPI1_CLK, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCSPI1_SIMO, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCSPI1_SOMI, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCSPI1_CS0, (PADCONF_PIN_NOT_USED))
    //DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCSPI1_CS1, (PADCONF_PIN_NOT_USED))
    //DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCSPI1_CS3, (PADCONF_PIN_NOT_USED))
    //DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCSPI1_CS2, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_4))/*GPIO_176*/   
DEVICE_PINMUX_END(OMAP_DEVICE_MCSPI1, D4)

//-----------------------------------------------------------------------------
// OMAP_DEVICE_MCSPI2
DEVICE_PINMUX_BEGIN(OMAP_DEVICE_MCSPI2, D0)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCSPI2_CLK, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCSPI2_SIMO, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCSPI2_SOMI, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCSPI2_CS0, (INPUT_DISABLE | PULL_DOWN | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCSPI2_CS1, (INPUT_DISABLE | PULL_DOWN | MUX_MODE_0))
DEVICE_PINMUX_END(OMAP_DEVICE_MCSPI2, D0)

DEVICE_PINMUX_BEGIN(OMAP_DEVICE_MCSPI2, D4)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCSPI2_CLK, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCSPI2_SIMO, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCSPI2_SOMI, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCSPI2_CS0, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MCSPI2_CS1, (PADCONF_PIN_NOT_USED)) 
DEVICE_PINMUX_END(OMAP_DEVICE_MCSPI2, D4)

//-----------------------------------------------------------------------------
// OMAP_DEVICE_UART1
DEVICE_PINMUX_BEGIN(OMAP_DEVICE_UART1, D0)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_UART1_TX, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_UART1_RTS, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_UART1_CTS, (INPUT_ENABLE | PULL_UP| MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_UART1_RX, (INPUT_ENABLE | PULL_UP | MUX_MODE_0))
DEVICE_PINMUX_END(OMAP_DEVICE_UART1, D0)

DEVICE_PINMUX_BEGIN(OMAP_DEVICE_UART1, D4)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_UART1_TX, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_UART1_RTS, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_UART1_CTS, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_UART1_RX, (PADCONF_PIN_NOT_USED))
DEVICE_PINMUX_END(OMAP_DEVICE_UART1, D4)

//-----------------------------------------------------------------------------
// OMAP_DEVICE_UART2
DEVICE_PINMUX_BEGIN(OMAP_DEVICE_UART2, D0)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_UART2_TX, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_UART2_RTS, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_UART2_CTS, (INPUT_ENABLE | PULL_UP| MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_UART2_RX, (INPUT_ENABLE | PULL_UP | MUX_MODE_0))
DEVICE_PINMUX_END(OMAP_DEVICE_UART2, D0)

DEVICE_PINMUX_BEGIN(OMAP_DEVICE_UART2, D4)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_UART2_TX, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_UART2_RTS, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_UART2_CTS, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_UART2_RX, (PADCONF_PIN_NOT_USED))
DEVICE_PINMUX_END(OMAP_DEVICE_UART2, D4)

//-----------------------------------------------------------------------------
// OMAP_DEVICE_UART3
DEVICE_PINMUX_BEGIN(OMAP_DEVICE_UART3, D0)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_UART3_TX_IRTX, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_UART3_RTS_SD, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_UART3_CTS_RCTX, (INPUT_ENABLE | PULL_UP | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_UART3_RX_IRRX, (INPUT_ENABLE | PULL_UP | MUX_MODE_0))
DEVICE_PINMUX_END(OMAP_DEVICE_UART3, D0)

DEVICE_PINMUX_BEGIN(OMAP_DEVICE_UART3, D4)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_UART3_TX_IRTX, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_UART3_RTS_SD, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_UART3_CTS_RCTX, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_UART3_RX_IRRX, (PADCONF_PIN_NOT_USED))
DEVICE_PINMUX_END(OMAP_DEVICE_UART3, D4)

//-----------------------------------------------------------------------------
// OMAP_DEVICE_UART4

// Not implemented on EVM

//-----------------------------------------------------------------------------
// OMAP_DEVICE_MMC1
DEVICE_PINMUX_BEGIN(OMAP_DEVICE_MMC1, D0)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MMC1_CLK, (INPUT_DISABLE | PULL_UP | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MMC1_CMD, (INPUT_ENABLE | PULL_UP | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MMC1_DAT0, (INPUT_ENABLE | PULL_UP | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MMC1_DAT1, (INPUT_ENABLE | PULL_UP | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MMC1_DAT2, (INPUT_ENABLE | PULL_UP | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MMC1_DAT3, (INPUT_ENABLE | PULL_UP | MUX_MODE_0))
DEVICE_PINMUX_END(OMAP_DEVICE_MMC1, D0)

DEVICE_PINMUX_BEGIN(OMAP_DEVICE_MMC1, D4)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MMC1_CLK, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MMC1_CMD, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MMC1_DAT0, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MMC1_DAT1, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MMC1_DAT2, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MMC1_DAT3, (PADCONF_PIN_NOT_USED))
DEVICE_PINMUX_END(OMAP_DEVICE_MMC1, D4)

//-----------------------------------------------------------------------------
// OMAP_DEVICE_MMC2
DEVICE_PINMUX_BEGIN(OMAP_DEVICE_MMC2, D0)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MMC2_CLK, (INPUT_ENABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MMC2_CMD, (INPUT_ENABLE | PULL_UP | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MMC2_DAT0, (INPUT_ENABLE | PULL_UP | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MMC2_DAT1, (INPUT_ENABLE | PULL_UP | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MMC2_DAT2, (INPUT_ENABLE | PULL_UP | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MMC2_DAT3, (INPUT_ENABLE | PULL_UP | MUX_MODE_0))
DEVICE_PINMUX_END(OMAP_DEVICE_MMC2, D0)

DEVICE_PINMUX_BEGIN(OMAP_DEVICE_MMC2, D4)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MMC2_CLK, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MMC2_CMD, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MMC2_DAT0, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MMC2_DAT1, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MMC2_DAT2, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_MMC2_DAT3, (PADCONF_PIN_NOT_USED))
DEVICE_PINMUX_END(OMAP_DEVICE_MMC2, D4)

//-----------------------------------------------------------------------------
// OMAP_DEVICE_CAMERA
DEVICE_PINMUX_BEGIN(OMAP_DEVICE_CAMERA, D0)
    //DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CSI2_DX0,(INPUT_ENABLE|PULL_INACTIVE|MUX_MODE_0))
    //DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CSI2_DY0,(INPUT_ENABLE|PULL_INACTIVE|MUX_MODE_0))
    //DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CSI2_DX1,(INPUT_ENABLE|PULL_INACTIVE|MUX_MODE_0))
    //DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CSI2_DY1,(INPUT_ENABLE|PULL_INACTIVE|MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_D0,  (INPUT_ENABLE|PULL_INACTIVE|MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_D1,  (INPUT_ENABLE|PULL_INACTIVE|MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_D2 , (INPUT_ENABLE| PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_D3 , (INPUT_ENABLE| PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_D4 , (INPUT_ENABLE| PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_D5 , (INPUT_ENABLE| PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_D6 , (INPUT_ENABLE| PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_D7 , (INPUT_ENABLE| PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_D8 , (INPUT_ENABLE| PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_D9 , (INPUT_ENABLE| PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_D10, (INPUT_ENABLE| PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_D11, (INPUT_ENABLE| PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_HS,  (INPUT_ENABLE|PULL_UP|MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_VS,  (INPUT_ENABLE|PULL_UP|MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_XCLKA, (INPUT_DISABLE|PULL_INACTIVE|MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_PCLK,  (INPUT_ENABLE|PULL_UP|MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_XCLKB,(INPUT_DISABLE|PULL_INACTIVE|MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_STROBE, (INPUT_DISABLE|PULL_INACTIVE|MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_WEN, (INPUT_ENABLE|PULL_UP|MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_FLD, (INPUT_ENABLE|PULL_UP|MUX_MODE_0))
DEVICE_PINMUX_END(OMAP_DEVICE_CAMERA, D0)

DEVICE_PINMUX_BEGIN(OMAP_DEVICE_CAMERA, D4)
    //DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CSI2_DX0,(PADCONF_PIN_NOT_USED))
    //DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CSI2_DY0,(PADCONF_PIN_NOT_USED))
    //DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CSI2_DX1,(PADCONF_PIN_NOT_USED))
    //DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CSI2_DY1,(PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_D0, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_D1, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_D2, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_D3, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_D4, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_D5, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_D6, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_D7, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_D8, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_D9, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_D10,(PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_D11,(PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_HS, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_VS, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_XCLKA, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_PCLK, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_XCLKB,(PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_STROBE, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_WEN, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_CAM_FLD, (PADCONF_PIN_NOT_USED))
DEVICE_PINMUX_END(OMAP_DEVICE_CAMERA, D4)

//-----------------------------------------------------------------------------
// OMAP_DEVICE_DSS
DEVICE_PINMUX_BEGIN(OMAP_DEVICE_DSS, D0)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_PCLK, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_HSYNC, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_VSYNC, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_ACBIAS, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA0, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA1, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA2, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA3, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA4, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA5, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA6, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA7, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA8, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA9, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA10, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA11, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA12, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA13, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA14, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA15, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA16, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA17, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA18, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA19, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA20, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA21, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA22, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA23, (INPUT_DISABLE | PULL_INACTIVE | MUX_MODE_0))
DEVICE_PINMUX_END(OMAP_DEVICE_DSS, D0)  

DEVICE_PINMUX_BEGIN(OMAP_DEVICE_DSS, D4)
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_PCLK, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_HSYNC, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_VSYNC, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_ACBIAS, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA0, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA1, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA2, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA3, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA4, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA5, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA6, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA7, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA8, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA9, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA10, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA11, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA12, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA13, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA14, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA15, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA16, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA17, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA18, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA19, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA20, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA21, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA22, (PADCONF_PIN_NOT_USED))
    DEVICE_PINMUX_ENTRY(CONTROL_PADCONF_DSS_DATA23, (PADCONF_PIN_NOT_USED))
DEVICE_PINMUX_END(OMAP_DEVICE_DSS, D4)  

//------------------------------------------------------------------------------
MAP_DEVICESTATE_BEGIN(OMAP_DEVICE_MCBSP2)
    MAP_DEVICESTATE_D0(OMAP_DEVICE_MCBSP2, D0)
    MAP_DEVICESTATE_D1(OMAP_DEVICE_MCBSP2, D0)
    MAP_DEVICESTATE_D2(OMAP_DEVICE_MCBSP2, D0)
    MAP_DEVICESTATE_D3(OMAP_DEVICE_MCBSP2, D4)
    MAP_DEVICESTATE_D4(OMAP_DEVICE_MCBSP2, D4)
MAP_DEVICESTATE_END(OMAP_DEVICE_MCBSP2)

MAP_DEVICESTATE_BEGIN(OMAP_DEVICE_MCBSP3)
    MAP_DEVICESTATE_D0(OMAP_DEVICE_MCBSP3, D0)
    MAP_DEVICESTATE_D1(OMAP_DEVICE_MCBSP3, D0)
    MAP_DEVICESTATE_D2(OMAP_DEVICE_MCBSP3, D0)
    MAP_DEVICESTATE_D3(OMAP_DEVICE_MCBSP3, D4)
    MAP_DEVICESTATE_D4(OMAP_DEVICE_MCBSP3, D4)
MAP_DEVICESTATE_END(OMAP_DEVICE_MCBSP3)

MAP_DEVICESTATE_BEGIN(OMAP_DEVICE_MCBSP4)
    MAP_DEVICESTATE_D0(OMAP_DEVICE_MCBSP4, D0)
    MAP_DEVICESTATE_D1(OMAP_DEVICE_MCBSP4, D0)
    MAP_DEVICESTATE_D2(OMAP_DEVICE_MCBSP4, D0)
    MAP_DEVICESTATE_D3(OMAP_DEVICE_MCBSP4, D4)
    MAP_DEVICESTATE_D4(OMAP_DEVICE_MCBSP4, D4)
MAP_DEVICESTATE_END(OMAP_DEVICE_MCBSP4)

MAP_DEVICESTATE_BEGIN(OMAP_DEVICE_HSOTGUSB)
    MAP_DEVICESTATE_D0(OMAP_DEVICE_HSOTGUSB, D0)
    MAP_DEVICESTATE_D1(OMAP_DEVICE_HSOTGUSB, D0)
    MAP_DEVICESTATE_D2(OMAP_DEVICE_HSOTGUSB, D0)
    MAP_DEVICESTATE_D3(OMAP_DEVICE_HSOTGUSB, D4)
    MAP_DEVICESTATE_D4(OMAP_DEVICE_HSOTGUSB, D4)
MAP_DEVICESTATE_END(OMAP_DEVICE_HSOTGUSB)

MAP_DEVICESTATE_BEGIN(OMAP_DEVICE_DSS)
    MAP_DEVICESTATE_D0(OMAP_DEVICE_DSS, D0)
    MAP_DEVICESTATE_D1(OMAP_DEVICE_DSS, D0)
    MAP_DEVICESTATE_D2(OMAP_DEVICE_DSS, D0)
    MAP_DEVICESTATE_D3(OMAP_DEVICE_DSS, D4)
    MAP_DEVICESTATE_D4(OMAP_DEVICE_DSS, D4)
MAP_DEVICESTATE_END(OMAP_DEVICE_DSS)

MAP_DEVICESTATE_BEGIN(OMAP_DEVICE_CAMERA)
    MAP_DEVICESTATE_D0(OMAP_DEVICE_CAMERA, D0)
    MAP_DEVICESTATE_D1(OMAP_DEVICE_CAMERA, D0)
    MAP_DEVICESTATE_D2(OMAP_DEVICE_CAMERA, D0)
    MAP_DEVICESTATE_D3(OMAP_DEVICE_CAMERA, D4)
    MAP_DEVICESTATE_D4(OMAP_DEVICE_CAMERA, D4)
MAP_DEVICESTATE_END(OMAP_DEVICE_CAMERA)

MAP_DEVICESTATE_BEGIN(OMAP_DEVICE_MMC1)
    MAP_DEVICESTATE_D0(OMAP_DEVICE_MMC1, D0)
    MAP_DEVICESTATE_D1(OMAP_DEVICE_MMC1, D0)
    MAP_DEVICESTATE_D2(OMAP_DEVICE_MMC1, D0)
    MAP_DEVICESTATE_D3(OMAP_DEVICE_MMC1, D4)
    MAP_DEVICESTATE_D4(OMAP_DEVICE_MMC1, D4)
MAP_DEVICESTATE_END(OMAP_DEVICE_MMC1)

MAP_DEVICESTATE_BEGIN(OMAP_DEVICE_MMC2)
    MAP_DEVICESTATE_D0(OMAP_DEVICE_MMC2, D0)
    MAP_DEVICESTATE_D1(OMAP_DEVICE_MMC2, D0)
    MAP_DEVICESTATE_D2(OMAP_DEVICE_MMC2, D0)
    MAP_DEVICESTATE_D3(OMAP_DEVICE_MMC2, D4)
    MAP_DEVICESTATE_D4(OMAP_DEVICE_MMC2, D4)
MAP_DEVICESTATE_END(OMAP_DEVICE_MMC2)

MAP_DEVICESTATE_BEGIN(OMAP_DEVICE_UART1)
    MAP_DEVICESTATE_D0(OMAP_DEVICE_UART1, D0)
    MAP_DEVICESTATE_D1(OMAP_DEVICE_UART1, D0)
    MAP_DEVICESTATE_D2(OMAP_DEVICE_UART1, D0)
    MAP_DEVICESTATE_D3(OMAP_DEVICE_UART1, D4)
    MAP_DEVICESTATE_D4(OMAP_DEVICE_UART1, D4)
MAP_DEVICESTATE_END(OMAP_DEVICE_UART1)

MAP_DEVICESTATE_BEGIN(OMAP_DEVICE_UART2)
    MAP_DEVICESTATE_D0(OMAP_DEVICE_UART2, D0)
    MAP_DEVICESTATE_D1(OMAP_DEVICE_UART2, D0)
    MAP_DEVICESTATE_D2(OMAP_DEVICE_UART2, D0)
    MAP_DEVICESTATE_D3(OMAP_DEVICE_UART2, D4)
    MAP_DEVICESTATE_D4(OMAP_DEVICE_UART2, D4)
MAP_DEVICESTATE_END(OMAP_DEVICE_UART2)

MAP_DEVICESTATE_BEGIN(OMAP_DEVICE_UART3)
    MAP_DEVICESTATE_D0(OMAP_DEVICE_UART3, D0)
    MAP_DEVICESTATE_D1(OMAP_DEVICE_UART3, D0)
    MAP_DEVICESTATE_D2(OMAP_DEVICE_UART3, D0)
    MAP_DEVICESTATE_D3(OMAP_DEVICE_UART3, D4)
    MAP_DEVICESTATE_D4(OMAP_DEVICE_UART3, D4)
MAP_DEVICESTATE_END(OMAP_DEVICE_UART3)

MAP_DEVICESTATE_BEGIN(OMAP_DEVICE_MCSPI1)
    MAP_DEVICESTATE_D0(OMAP_DEVICE_MCSPI1, D0)
    MAP_DEVICESTATE_D1(OMAP_DEVICE_MCSPI1, D0)
    MAP_DEVICESTATE_D2(OMAP_DEVICE_MCSPI1, D0)
    MAP_DEVICESTATE_D3(OMAP_DEVICE_MCSPI1, D4)
    MAP_DEVICESTATE_D4(OMAP_DEVICE_MCSPI1, D4)
MAP_DEVICESTATE_END(OMAP_DEVICE_MCSPI1)

MAP_DEVICESTATE_BEGIN(OMAP_DEVICE_MCSPI2)
    MAP_DEVICESTATE_D0(OMAP_DEVICE_MCSPI2, D0)
    MAP_DEVICESTATE_D1(OMAP_DEVICE_MCSPI2, D0)
    MAP_DEVICESTATE_D2(OMAP_DEVICE_MCSPI2, D0)
    MAP_DEVICESTATE_D3(OMAP_DEVICE_MCSPI2, D4)
    MAP_DEVICESTATE_D4(OMAP_DEVICE_MCSPI2, D4)
MAP_DEVICESTATE_END(OMAP_DEVICE_MCSPI2)

MAP_DEVICESTATE_BEGIN(OMAP_DEVICE_HDQ)
    MAP_DEVICESTATE_D0(OMAP_DEVICE_HDQ, D0)
    MAP_DEVICESTATE_D1(OMAP_DEVICE_HDQ, D0)
    MAP_DEVICESTATE_D2(OMAP_DEVICE_HDQ, D0)
    MAP_DEVICESTATE_D3(OMAP_DEVICE_HDQ, D4)
    MAP_DEVICESTATE_D4(OMAP_DEVICE_HDQ, D4)
MAP_DEVICESTATE_END(OMAP_DEVICE_HDQ)

MAP_DEVICESTATE_BEGIN(OMAP_DEVICE_USBHOST1)
    MAP_DEVICESTATE_D0(OMAP_DEVICE_USBHOST1, D0)
    MAP_DEVICESTATE_D1(OMAP_DEVICE_USBHOST1, D0)
    MAP_DEVICESTATE_D2(OMAP_DEVICE_USBHOST1, D0)
    MAP_DEVICESTATE_D3(OMAP_DEVICE_USBHOST1, D4)
    MAP_DEVICESTATE_D4(OMAP_DEVICE_USBHOST1, D4)
MAP_DEVICESTATE_END(OMAP_DEVICE_USBHOST1)

MAP_DEVICESTATE_BEGIN(OMAP_DEVICE_USBHOST2)
    MAP_DEVICESTATE_D0(OMAP_DEVICE_USBHOST2, D0)
    MAP_DEVICESTATE_D1(OMAP_DEVICE_USBHOST2, D0)
    MAP_DEVICESTATE_D2(OMAP_DEVICE_USBHOST2, D0)
    MAP_DEVICESTATE_D3(OMAP_DEVICE_USBHOST2, D4)
    MAP_DEVICESTATE_D4(OMAP_DEVICE_USBHOST2, D4)
MAP_DEVICESTATE_END(OMAP_DEVICE_USBHOST2)

MAP_DEVICESTATE_BEGIN(OMAP_DEVICE_USBHOST3)
    MAP_DEVICESTATE_D0(OMAP_DEVICE_USBHOST3, D0)
    MAP_DEVICESTATE_D1(OMAP_DEVICE_USBHOST3, D0)
    MAP_DEVICESTATE_D2(OMAP_DEVICE_USBHOST3, D0)
    MAP_DEVICESTATE_D3(OMAP_DEVICE_USBHOST3, D4)
    MAP_DEVICESTATE_D4(OMAP_DEVICE_USBHOST3, D4)
MAP_DEVICESTATE_END(OMAP_DEVICE_USBHOST3)

//------------------------------------------------------------------------------
//
//  Function:  _OALMUX_UpdatePinMux
//
//  utility routine which performs the pinmuxing.
//
static
void
_OALMUX_UpdatePinMux(
    DEVICE_PINMUX_ENTRY_t  *pPinMuxEntries
    )
{
    // validate parameters
    if (pPinMuxEntries == NULL) return;

    // iterate through list and perform pin-muxing
    while (pPinMuxEntries->offset != -1)
        {
        OUTREG16(((DWORD)_pSyscConfigContext + pPinMuxEntries->offset), 
            pPinMuxEntries->value
            );
        ++pPinMuxEntries;
        }
}

//------------------------------------------------------------------------------
//
//  Function:  OALMux_InitMuxTable
//
//  initialization for pinmux on device state change.
//
void
OALMux_InitMuxTable(
    )
{
    // NOTE:
    //  excluding i2c from list to reduce potential overhead since the i2c 
    // drivers power state gets frequently called 
    //
    
    // NOTE:
    //  excluding most drivers from pinmux list since a limited amount of
    // testing has been implemented.
    
    // map pointer to sysconfig registers
    _pSyscConfigContext = OALPAtoUA(OMAP_SYSC_PADCONFS_REGS_PA);

    // initialize device pin mux table
    memset(_rgDeviceMux, 0, sizeof(_rgDeviceMux));
    
    // pin-mux for display
    // ??? disable DSS pin muxing
    //_rgDeviceMux[OMAP_DEVICE_DSS] = DEVICESTATE_MUX_NAME(OMAP_DEVICE_DSS);

    // pin-mux for hdq/1-wire
    //_rgDeviceMux[OMAP_DEVICE_HDQ] = DEVICESTATE_MUX_NAME(OMAP_DEVICE_HDQ);  

    // pin-mux for mmc
    //_rgDeviceMux[OMAP_DEVICE_MMC1] = DEVICESTATE_MUX_NAME(OMAP_DEVICE_MMC1);
    //_rgDeviceMux[OMAP_DEVICE_MMC2] = DEVICESTATE_MUX_NAME(OMAP_DEVICE_MMC2);

    // pin-mux for camera/csi2
    //_rgDeviceMux[OMAP_DEVICE_CAMERA] = DEVICESTATE_MUX_NAME(OMAP_DEVICE_CAMERA); 

    // pin-mux for mcbsp
    _rgDeviceMux[OMAP_DEVICE_MCBSP2] = DEVICESTATE_MUX_NAME(OMAP_DEVICE_MCBSP2);
    //_rgDeviceMux[OMAP_DEVICE_MCBSP3] = DEVICESTATE_MUX_NAME(OMAP_DEVICE_MCBSP3);
    //_rgDeviceMux[OMAP_DEVICE_MCBSP4] = DEVICESTATE_MUX_NAME(OMAP_DEVICE_MCBSP4);

    // pin-mux for spi
    //_rgDeviceMux[OMAP_DEVICE_MCSPI1] = DEVICESTATE_MUX_NAME(OMAP_DEVICE_MCSPI1);
    _rgDeviceMux[OMAP_DEVICE_MCSPI2] = DEVICESTATE_MUX_NAME(OMAP_DEVICE_MCSPI2);    
}

//------------------------------------------------------------------------------
//
//  Function:  OALMux_UpdateOnDeviceStateChange
//
//  called before and after a device state change.
//
DWORD
OALMux_UpdateOnDeviceStateChange(
    UINT devId,
    UINT oldState,
    UINT newState,
    BOOL bPreStateChange
    )
{
    DWORD rc = -1;
    DEVICE_PINMUX_t *pDeviceMuxTbl;
    
    if (_rgDeviceMux[devId] == NULL) 
	    return rc;

    rc = 0;
    // Don't do anything on pre-device state notification if we are 
    // transitioning to a higher power state (lower Dn number).
    // Don't do anything on post-device state notification if we are 
    // transitioning to a lower power state (higher Dn number).
    if ((bPreStateChange == FALSE && newState < oldState) ||
        (bPreStateChange != FALSE && newState > oldState))
        {
        // device is about to be activated and after state change or
        // device is about to be de-activated and before state change
        pDeviceMuxTbl = _rgDeviceMux[devId]; 
        if ((*pDeviceMuxTbl)[newState] != (*pDeviceMuxTbl)[oldState])
            {
            _OALMUX_UpdatePinMux((*pDeviceMuxTbl)[newState]);
            }

        // save pinmux context
        OALContextUpdateDirtyRegister(HAL_CONTEXTSAVE_PINMUX);
        
        rc = 1;
        }
 
    return rc;
}


//-----------------------------------------------------------------------------

