@echo off

REM Initial environment configuration

set _PB_INSTALL_ROOT=C:\PROGRA~1\MIFAB2~1\6.00
set USING_PB_WORKSPACE_ENVIRONMENT=1
set _WINCEROOT=C:\WINCE600
set _FLATRELEASEDIR=C:\WINCE600\OSDesigns\ce317_mini\ce317_mini\RelDir\TI_EVM_3530_ARMV4I_Release
set LOCALE=0409
set _PROJECTROOT=C:\WINCE600\OSDesigns\ce317_mini\ce317_mini\Wince600\TI_EVM_3530_ARMV4I

REM Workspace and configuration variables

set PBWORKSPACE=C:\WINCE600\OSDesigns\ce317_mini\ce317_mini\ce317_mini.pbxml
set PBWORKSPACEROOT=C:\WINCE600\OSDesigns\ce317_mini\ce317_mini
set PBCONFIG=TI_EVM_3530_ARMV4I Release

REM Call wince.bat

call C:\WINCE600\public\COMMON\OAK\MISC\wince.bat ARMV4I ce317_mini TI_EVM_3530

REM Make sure all build options are turned off

set IMGNODEBUGGER=
set IMGNOKITL=
set IMGEBOOT=
set IMGFLASH=
set IMGPROFILER=
set IMGCELOGENABLE=
set IMGAUTOFLUSH=
set IMGOSCAPTURE=
set BUILDREL_USE_COPY=
set WINCESHIP=
set IMGRAM64=
set IMGHDSTUB=

REM Anchored features

set SYSGEN_AS_BASE=1
set SYSGEN_PEGTERM=1
set SYSGEN_CPP_EH_AND_RTTI=1
set SYSGEN_FULL_CRT=1
set SYSGEN_STDIO=1
set SYSGEN_STDIOA=1
set SYSGEN_CORESTRA=1
set SYSGEN_STRSAFE=1
set SYSGEN_NETUTILS=1
set SYSGEN_WINSOCK=1
set SYSGEN_AUTORAS=1
set SYSGEN_MODEM=1
set SYSGEN_UNIMODEM=1
set SYSGEN_SERVICES=1
set SYSGEN_FTPD=1
set SYSGEN_BATTERY=1
set SYSGEN_TOOLHELP=1
set SYSGEN_DISPLAY=1
set SYSGEN_SHELL=1
set SYSGEN_NOTIFY=1
set SYSGEN_USBFN=1
set SYSGEN_USB=1
set SYSGEN_USB_HID_KEYBOARD=1
set SYSGEN_USB_STORAGE=1
set SYSGEN_FSRAMROM=1
set SYSGEN_FSREGHIVE=1
set SYSGEN_EXFAT=1
set SYSGEN_MSPART=1
set SYSGEN_RELFSD=1
set SYSGEN_STOREMGR_CPL=1
set SYSGEN_TFAT=1
set SYSGEN_AUDIO=1
set SYSGEN_DDRAW=1
set SYSGEN_DSHOW_MP3=1
set SYSGEN_DSHOW_WAV=1
set SYSGEN_DSHOW_WMA=1
set SYSGEN_DSHOW_ICM=1
set SYSGEN_DSHOW_WMV=1
set SYSGEN_CORELOC=1
set SYSGEN_CMD=1
set SYSGEN_CONSOLE=1
set SYSGEN_STANDARDSHELL=1
set SYSGEN_COMMCTRL=1
set SYSGEN_COMMDLG=1
set SYSGEN_CTLPNL=1
set SYSGEN_CONNMC=1
set SYSGEN_LARGEKB=1
set SYSGEN_TOUCH=1
set SYSGEN_WCELOAD=1
set SYSGEN_ACM_MSFILTER=1
set SYSGEN_ACM_GSM610=1
set SYSGEN_IMAGING_BMP_DECODE=1
set SYSGEN_IMAGING_GIF_DECODE=1
set SYSGEN_IMAGING_ICO_DECODE=1
set SYSGEN_IMAGING_JPG_DECODE=1
set SYSGEN_IMAGING_TIFF_DECODE=1
set SYSGEN_IMAGING_PNG_DECODE=1
set SYSGEN_DSHOW_MSG711=1
set SYSGEN_DSHOW_MSGSM610=1
set SYSGEN_DSHOW_IMAADPCM=1
set SYSGEN_DSHOW_MPEGA=1
set SYSGEN_DSHOW_MSADPCM=1
set SYSGEN_DSHOW_WAVEOUT=1
set SYSGEN_DSHOW_WMA_VOICE=1
set SYSGEN_DSHOW_AVI=1
set SYSGEN_DSHOW_MPEGV=1
set SYSGEN_MENU_OVERLAP=1
set SYSGEN_USBFN_SERIAL=1
set SYSGEN_USBFN_STORAGE=1
set BSP_FLASHFX=1
set SYSGEN_ETH_80211=1
set WL1271_WLAN=1
set HOST_PLAT_EVM_OMAP3530=1
set WL1271_SDIO_OPTIMIZED=1
set SYSGEN_ETH_80211=1
set SYSGEN_BTH=1
set WL1271_BTH=1
set HOST_PLAT_EVM_OMAP3530=1
set BSP_COM2=1
set BSP_WL1271_APPLET=1
set BSP_WL1271_APP=1
set SYSGEN_PVR_SGXCOREREV_125=1
set SYSGEN_PVR_OPENGLES1=1
set PVR_OPENGLES1=1
set SYSGEN_PVR_OPENGLES2=1
set PVR_OPENGLES2=1
set SYSGEN_PVR_OPENVG=1
set PVR_OPENVG=1
set SYSGEN_SDBUS=1
set IMGSDBUS2=1
set SYSGEN_SD_MEMORY=1
set SYSGEN_GDI_ALPHABLEND=1
set SYSGEN_CEPLAYER=1
set SYSGEN_MEDIAAPPS_WMPOCX=1
set SYSGEN_LOCALAUDIO=1
set SYSGEN_D3DM=1
set SYSGEN_IMAGING_BMP_ENCODE=1
set SYSGEN_IMAGING_GIF_ENCODE=1
set SYSGEN_IMAGING_JPG_ENCODE=1
set SYSGEN_IMAGING_PNG_ENCODE=1
set SYSGEN_IMAGING_TIFF_ENCODE=1
set SYSGEN_DSHOW_WMASPDTXDMO=1
set SYSGEN_DSHOW_WMT_NSC=1
set SYSGEN_DSHOW_WMT_ASXV2=1
set SYSGEN_DSHOW_WMT_LOCAL=1
set SYSGEN_AYGSHELL=1
set SYSGEN_GESTUREANIMATION=1
set SYSGEN_TOUCHGESTURE=1
set SYSGEN_XAML_RUNTIME=1
set SYSGEN_MENU_TAP_UI=1
set SYSGEN_COMMCTRL_ANIMATE=1
set SYSGEN_AUTH_SCHANNEL=1
set SYSGEN_IE_FLASHLITE=1
set SYSGEN_IESAMPLE_EXR=1
set SYSGEN_USB_PRINTER=1
set SYSGEN_BTH_PAN=1
set SYSGEN_BTH_GATEWAY=1
set SYSGEN_BTH_HID_KEYBOARD=1
set SYSGEN_OBEX_CLIENT=1
set SYSGEN_OBEX_INBOX=1
set SYSGEN_OBEX_FILEBROWSER=1
set SYSGEN_LAP_PSWD=1
set SYSGEN_ENROLL=1

REM BSP features

set BSP_COM1=1
set BSP_COM2=1
set BSP_COM3=1
set SYSGEN_POWERVR=1
set PVR_SERVICES4=1
set BSP_LIGHTSENSE=1
set BSP_AIODRIVER=1

REM Misc settings

set WINCEDEBUG=retail
set PATH=%PATH%;C:\Windows\system32;C:\Windows;C:\Program Files\Microsoft Platform Builder\6.00\cepb\IdeVS

REM Configuration environment variables


REM Build options

set IMGEBOOT=1
set IMGNODEBUGGER=1
set IMGNOKITL=1
set IMGAUTOFLUSH=1
set BUILDREL_USE_COPY=1
set ri_suppress_info=all
set BUILD_MULTIPROCESSOR=1

REM Project settings

set _USER_SYSGEN_BAT_FILES=C:\WINCE600\3rdparty\datalight\flashfx\projects\ProjSysgen.bat C:\WINCE600\3rdparty\adeneoembedded\drivers\wilink_6.0\ProjSysgen.bat C:\WINCE600\OSDesigns\ce317_mini\ce317_mini\Wince600\TI_EVM_3530_ARMV4I\OAK\MISC\ce317_mini.bat

REM Locale options

set IMGNOLOC=0
set IMGSTRICTLOC=0
