#ifndef CAN_DEBUG_H
	#define CAN_DEBUG_H
	#ifdef DEBUG
		#define	ZONEID_INIT			0
		#define	ZONEID_DEINIT		1
		#define	ZONEID_POWER		2
		#define	ZONEID_SPI			3
		#define ZONEID_SPIE			4
		#define	ZONEID_MCP2515		5
		#define	ZONEID_CAN			6
		#define	ZONEID_STEPS		7
		#define	ZONEID_WARNING		14
		#define	ZONEID_ERROR		15

		#define ZONE_INIT			DEBUGZONE(ZONEID_INIT)
		#define ZONE_DEINIT			DEBUGZONE(ZONEID_DEINIT)		
		#define ZONE_POWER			DEBUGZONE(ZONEID_POWER)
		#define ZONE_SPI			DEBUGZONE(ZONEID_SPI)
		#define ZONE_SPIE			DEBUGZONE(ZONEID_SPIE)
		#define ZONE_MCP2515		DEBUGZONE(ZONEID_MCP2515)
		#define ZONE_CAN			DEBUGZONE(ZONEID_CAN)
		#define ZONE_STEPS			DEBUGZONE(ZONEID_STEPS)
		#define ZONE_WARNING		DEBUGZONE(ZONEID_WARNING)
		#define ZONE_ERROR			DEBUGZONE(ZONEID_ERROR)

		#define	ZONEMASK_INIT		(1<<ZONEID_INIT)
		#define	ZONEMASK_DEINIT		(1<<ZONEID_DEINIT)
		#define	ZONEMASK_POWER		(1<<ZONEID_POWER)
		#define	ZONEMASK_SPI		(1<<ZONEID_SPI)
		#define	ZONEMASK_SPIE		(1<<ZONEID_SPIE)
		#define	ZONEMASK_MCP2515	(1<<ZONEID_MCP2515)
		#define	ZONEMASK_CAN		(1<<ZONEID_CAN)
		#define	ZONEMASK_STEPS		(1<<ZONEID_STEPS)
		#define	ZONEMASK_WARNING	(1<<ZONEID_WARNING)
		#define	ZONEMASK_ERROR		(1<<ZONEID_ERROR)

		extern DBGPARAM dpCurSettings;
	#endif	// DEBUG
#endif
